#!/bin/bash

################################################################
#   Replace the NetIDs form showq for a given account with the #
#   Last Names of the users.                                   #
#   Uses a python script to do the replacements                #
#   Arguments - Account Name                                   #
#                                                              #
#   Author: Adam Dempsey                                       #
#                                                              #
################################################################


ACCT=$1

module load utilities

FILE1=$(mktemp /tmp/showus.XXXXX)
FILE2=$(mktemp /tmp/showus.XXXXX)


showq  -w acct=$ACCT $2 > $FILE1

grouplist $ACCT > $FILE2

python $HOME/QuestScripts/queviewer.py $FILE1 $FILE2

cat $FILE1 

rm -f $FILE1 $FILE2



