#!/bin/bash

#######################################################################
#   Display the usage information for the whole cluster.              #
#   This script will output the NetID and the total number of         #
#   Running, Idle, SystemHold, and Blocked jobs for every user.       #
#   Additionally, we output the total usage of Running jobs for every #
#   account.                                                          #
#                                                                     #
#   Author: Adam Dempsey                                              #
#                                                                     #
#######################################################################


printf "\nUsage by Name\n\n"
printf "%10s\t%5s\t%5s\t%5s\t%5s\n" "NetID"  "Running"   " Idle" "Hold" "Blocked"
printf "%.0s-" {1..45}
printf "\n"


FILE1=$(mktemp /tmp/total_usage.XXXXXX)
FILE2=$(mktemp /tmp/total_usage.XXXXXX)
FILE3=$(mktemp /tmp/total_usage.XXXXXX)

showq  > $FILE1


RUNNING=( $(cat $FILE1 | grep -E 'Running|Idle|SystemHold|Blocked' | awk '{print $2}' | sort | uniq) )

TOTRUNNING=0
TOTIDLE=0
TOTHOLD=0
TOTBLOCK=0

for i in ${RUNNING[@]}
do
    TOTR=$( cat $FILE1 | grep $i | grep Running | awk '{s+=$4} END {print s}')
    TOTI=$( cat $FILE1 | grep $i | grep Idle | awk '{s+=$4} END {print s}')
    TOTH=$( cat $FILE1 | grep $i | grep SystemHold | awk '{s+=$4} END {print s}')
    TOTB=$( cat $FILE1 | grep $i | grep Blocked | awk '{s+=$4} END {print s}')
    
    if [[  -z "${TOTR// }" ]]; then
        TOTR=0
    fi
    if [[  -z "${TOTI// }" ]]; then
        TOTI=0
    fi
    if [[  -z "${TOTH// }" ]]; then
        TOTH=0
    fi
    if [[  -z "${TOTB// }" ]]; then
        TOTB=0
    fi

    TOTRUNNING=$(($TOTRUNNING + $TOTR))
    TOTIDLE=$(($TOTIDLE + $TOTI))
    TOTHOLD=$(($TOTHOLD + $TOTH))
    TOTBLOCK=$(($TOTBLOCK + $TOTB))

    printf "%10s\t%5s\t%5s\t%5s\t%5s\n" "$i" "$TOTR" "$TOTI" "$TOTH" "$TOTB" >> $FILE2 


done

cat $FILE2 | sort -k2 -n -r


showq -r | grep  'R' | grep -v "USERNAME" > $FILE1
ACCT=( $(cat $FILE1 | awk '{print $8}' | sort | uniq) )

printf "\nUsage by Account\n\n"
printf "%10s\t%5s\t%5s\t%5s\t%5s\n" "NetID"  "Running"   " Idle" "Hold" "Blocked"
printf "%.0s-" {1..45}
printf "\n"
for i in ${ACCT[@]}
do
    TOTR=$( cat $FILE1 | grep $i  | awk '{s+=$10} END {print s}')
    
    if [[  -z "${TOTR// }" ]]; then
        TOTR=0
    fi

    printf "%10s\t%5s\t%5s\t%5s\t%5s\n" "$i" "$TOTR" "N/A" "N/A" "N/A" >> $FILE3 

done

cat $FILE3 | sort -k2 -n -r
printf "%.0s-" {1..45}
printf "\n"
printf "%10s\t%5s\t%5s\t%5s\t%5s\n" "TOTALS" "$TOTRUNNING" "$TOTIDLE" "$TOTHOLD" "$TOTBLOCK" 


rm -f "$FILE1" "$FILE2" "$FILE3"
